"""Add batch checkpoint table

Revision ID: 1f39d316eec9
Revises: a58508c0fc38
Create Date: 2026-05-30 07:56:58.489573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f39d316eec9'
down_revision: Union[str, Sequence[str], None] = 'a58508c0fc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('step_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'step_name', name='uq_job_step')
    )
    op.create_index(op.f('ix_batch_checkpoints_job_id'), 'batch_checkpoints', ['job_id'], unique=False)
    op.create_index(op.f('ix_batch_checkpoints_status'), 'batch_checkpoints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_checkpoints_status'), table_name='batch_checkpoints')
    op.drop_index(op.f('ix_batch_checkpoints_job_id'), table_name='batch_checkpoints')
    op.drop_table('batch_checkpoints')
    # ### end Alembic commands ###
