"""add_symbol_type_to_symbols

Revision ID: 615f876db25d
Revises: 1f39d316eec9
Create Date: 2026-06-09 11:23:58.500540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615f876db25d'
down_revision: Union[str, Sequence[str], None] = '1f39d316eec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('symbol_type', sa.String(length=20), nullable=False, server_default='stock'))
    op.create_index(op.f('ix_symbols_symbol_type'), 'symbols', ['symbol_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol_type'), table_name='symbols')
    op.drop_column('symbols', 'symbol_type')
    # ### end Alembic commands ###
