"""Add composite indexes for query optimization

Revision ID: a58508c0fc38
Revises: f296d0e00335
Create Date: 2026-05-28 13:35:44.575509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58508c0fc38'
down_revision: Union[str, Sequence[str], None] = 'f296d0e00335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_benchmark_daily_prices_benchmark_trade_date', 'benchmark_daily_prices', ['benchmark_id', 'trade_date'], unique=False)
    op.create_index('ix_daily_prices_symbol_trade_date', 'daily_prices', ['symbol_id', 'trade_date'], unique=False)
    op.create_index('ix_rs_scores_trade_date_market_rating', 'rs_scores', ['trade_date', 'market', 'rs_rating'], unique=False)
    op.create_index('ix_symbols_market_active', 'symbols', ['market', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symbols_market_active', table_name='symbols')
    op.drop_index('ix_rs_scores_trade_date_market_rating', table_name='rs_scores')
    op.drop_index('ix_daily_prices_symbol_trade_date', table_name='daily_prices')
    op.drop_index('ix_benchmark_daily_prices_benchmark_trade_date', table_name='benchmark_daily_prices')
    # ### end Alembic commands ###
