"""Initial migration

Revision ID: f296d0e00335
Revises: 
Create Date: 2026-05-28 13:34:07.468948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f296d0e00335'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_benchmark_code'), 'benchmarks', ['benchmark_code'], unique=True)
    op.create_index(op.f('ix_benchmarks_market'), 'benchmarks', ['market'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=False),
    sa.Column('symbols_succeeded', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_job_type'), 'crawl_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_code'), 'symbols', ['code'], unique=True)
    op.create_index(op.f('ix_symbols_market'), 'symbols', ['market'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_table('benchmark_daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_id', 'trade_date', name='uq_benchmark_daily_prices_id_date')
    )
    op.create_index(op.f('ix_benchmark_daily_prices_benchmark_id'), 'benchmark_daily_prices', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_benchmark_daily_prices_trade_date'), 'benchmark_daily_prices', ['trade_date'], unique=False)
    op.create_table('crawl_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_class', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_failures_job_id'), 'crawl_failures', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawl_failures_target_key'), 'crawl_failures', ['target_key'], unique=False)
    op.create_index(op.f('ix_crawl_failures_target_type'), 'crawl_failures', ['target_type'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('change_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'trade_date', name='uq_daily_prices_symbol_date')
    )
    op.create_index(op.f('ix_daily_prices_symbol_id'), 'daily_prices', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_daily_prices_trade_date'), 'daily_prices', ['trade_date'], unique=False)
    op.create_table('rs_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('return_3m', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('return_6m', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('return_9m', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('return_12m', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('relative_return_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('rs_percentile', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('rs_rating', sa.Integer(), nullable=False),
    sa.Column('rank_in_market', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'trade_date', name='uq_rs_scores_symbol_date')
    )
    op.create_index(op.f('ix_rs_scores_benchmark_id'), 'rs_scores', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_rs_scores_market'), 'rs_scores', ['market'], unique=False)
    op.create_index(op.f('ix_rs_scores_rank_in_market'), 'rs_scores', ['rank_in_market'], unique=False)
    op.create_index(op.f('ix_rs_scores_relative_return_score'), 'rs_scores', ['relative_return_score'], unique=False)
    op.create_index(op.f('ix_rs_scores_rs_rating'), 'rs_scores', ['rs_rating'], unique=False)
    op.create_index(op.f('ix_rs_scores_symbol_id'), 'rs_scores', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_rs_scores_trade_date'), 'rs_scores', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rs_scores_trade_date'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_symbol_id'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_rs_rating'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_relative_return_score'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_rank_in_market'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_market'), table_name='rs_scores')
    op.drop_index(op.f('ix_rs_scores_benchmark_id'), table_name='rs_scores')
    op.drop_table('rs_scores')
    op.drop_index(op.f('ix_daily_prices_trade_date'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_symbol_id'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_crawl_failures_target_type'), table_name='crawl_failures')
    op.drop_index(op.f('ix_crawl_failures_target_key'), table_name='crawl_failures')
    op.drop_index(op.f('ix_crawl_failures_job_id'), table_name='crawl_failures')
    op.drop_table('crawl_failures')
    op.drop_index(op.f('ix_benchmark_daily_prices_trade_date'), table_name='benchmark_daily_prices')
    op.drop_index(op.f('ix_benchmark_daily_prices_benchmark_id'), table_name='benchmark_daily_prices')
    op.drop_table('benchmark_daily_prices')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_market'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_code'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_job_type'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_benchmarks_market'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_benchmark_code'), table_name='benchmarks')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
